version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - ./app:/var/www/app
      - ./resources:/var/www/resources
      - ./routes:/var/www/routes
      - laravel_vendor:/var/www/vendor
      - laravel_node_modules:/var/www/node_modules
    ports:
      - "8000:8000"        # Laravel dev server
      - "5173:5173"        # Vite dev server
    environment:
      - CHOKIDAR_USEPOLLING=true  # Helps Vite hot reload work inside Docker
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
volumes:
  laravel_vendor:
  laravel_node_modules:
